variable "vpc-cidr" {}
variable "tag-vpc" {}
variable "pubsub01-cidr" {}
variable "az1" {}
variable "tag-pubsub01" {}
variable "pubsub02-cidr" {}
variable "az2" {}
variable "tag-pubsub02" {}
variable "prvtsub01-cidr" {}
variable "tag-prvtsub01" {}
variable "prvtsub02-cidr" {}
variable "tag-prvtsub02" {}
variable "tag-igw" {}
variable "cidr-all" {}
variable "tag-public-subnet-RT" {}
variable "tag-EIP" {}
variable "tag-nat-gateway" {}
variable "tag-private-route-table" {}
variable "port_ssh" {}
variable "port_sonar" {}
variable "sonarqube-sg" {}
variable "port_http" {}
variable "Jenkins_SG" {}
variable "bastion-ansible-sg" {}
variable "Nexus_SG" {}
variable "port_nexus" {}
variable "port_nexus2" {}
variable "RDS_SG" {}
variable "mysql_port" {}
variable "port_proxy" {}
variable "port_https" {}
variable "docker-SG" {}
variable "keypair_name" {}