variable "ami_redhat" {}
variable "instance_type" {}
variable "subnet_id" {}
variable "bastion-ansible-sg" {}
variable "key_name" {}
variable "tag-ansible" {}
variable "stage-playbook" {}
variable "prod-playbook" {}
variable "stage-bash-script" {}
variable "prod-bash-script" {}
variable "private-key" {}
variable "nexus-ip" {}