variable "ami" {}
variable "instance_type" {}
variable "prt_subnet" {}
variable "security_group" {}
variable "key_name" {}
variable "tag-jenkins-server" {}
variable "jenkins-elb" {}
variable "subnet-id" {}
variable "nexus-ip" {}
variable "newrelic-user-licence" {}
variable "newrelic-acct-id" {}