variable "ami-redhat-id" {}
variable "instance_type" {}
variable "stage-lt-sg" {}
variable "keypair_name" {}
variable "stage-asg-name" {}
variable "vpc-zone-identifier" {}
variable "tg-arn" {}
variable "asg-policy" {}
variable "nexus-ip" {}
variable "newrelic-user-licence" {}
variable "newrelic-acct-id" {}